name: release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull core submodule
        run: git submodule update --init --recursive
      
      - name: Use php composer
        uses: php-actions/composer@v6
        with:
          php_version: 7.4

      # Not working because wordpress is outside of the repo code
      # - name: Downgrade code
      #   run: composer run rector

      - name: Uninstall dev deps
        run: sudo composer update --no-dev

      - name: Compress plugin source
        uses: master-atul/tar-action@v1.0.2
        id: compress_plugin
        with:
          command: c
          files: |
            ./src
            ./vendor
            ./wp-miogest-sync.php
            ./sync.php
            ./composer.json
            ./composer.lock
            ./README.md
          outPath: wp-miogest-sync.tar.gz

      - name: Compress modified themes and plugins of Resideo
        uses: master-atul/tar-action@v1.0.2
        id: compress_resideo
        with:
          command: c
          files: |
            ./themes_plugins_modified
            ./README.md
          outPath: wp-miogest-sync-resideo-modified.tar.gz

      - name: Get version of the project
        id: project-version
        uses: 'euberdeveloper/ga-project-version@main'
        with:
          package-manager: 'composer'

      - name: Add release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.project-version.outputs.version }}"
          prerelease: false
          title: "Deploy Wp Miogest Sync Plugin"
          files: |
            wp-miogest-sync.tar.gz
            wp-miogest-sync-resideo-modified.tar.gz
